# This workflow will build a goplus project
name: Go+

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go/Go+
      uses: goplus/setup-goplus@v1
      with:
        go-version: "1.18"
        gop-version: "1.1.8"

    - name: Build
      run: |
        gop go -t -s ./...
